=begin
#Connectwise Manage All Endpoints

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2022.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.2.1

=end

require 'date'
require 'time'

module ConnectWise
  class ExportAccountingBatchRequest
    #  Max length: 50;
    attr_accessor :batch_identifier

    attr_accessor :gl_interface_identifier

    attr_accessor :thru_date

    attr_accessor :location_id

    attr_accessor :summarize_invoices

    # Batch export must include invoices, expenses, or products (procurement)
    attr_accessor :export_invoices_flag

    attr_accessor :included_invoice_ids

    attr_accessor :excluded_invoice_ids

    # Batch export must include invoices, expenses, or products (procurement)
    attr_accessor :export_expenses_flag

    attr_accessor :included_expense_ids

    attr_accessor :excluded_expense_ids

    # Batch export must include invoices, expenses, or products (procurement)
    attr_accessor :export_products_flag

    attr_accessor :included_product_ids

    attr_accessor :excluded_product_ids

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'batch_identifier' => :'batchIdentifier',
        :'gl_interface_identifier' => :'glInterfaceIdentifier',
        :'thru_date' => :'thruDate',
        :'location_id' => :'locationId',
        :'summarize_invoices' => :'summarizeInvoices',
        :'export_invoices_flag' => :'exportInvoicesFlag',
        :'included_invoice_ids' => :'includedInvoiceIds',
        :'excluded_invoice_ids' => :'excludedInvoiceIds',
        :'export_expenses_flag' => :'exportExpensesFlag',
        :'included_expense_ids' => :'includedExpenseIds',
        :'excluded_expense_ids' => :'excludedExpenseIds',
        :'export_products_flag' => :'exportProductsFlag',
        :'included_product_ids' => :'includedProductIds',
        :'excluded_product_ids' => :'excludedProductIds'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'batch_identifier' => :'String',
        :'gl_interface_identifier' => :'String',
        :'thru_date' => :'Time',
        :'location_id' => :'Integer',
        :'summarize_invoices' => :'String',
        :'export_invoices_flag' => :'Boolean',
        :'included_invoice_ids' => :'Array<Integer>',
        :'excluded_invoice_ids' => :'Array<Integer>',
        :'export_expenses_flag' => :'Boolean',
        :'included_expense_ids' => :'Array<Integer>',
        :'excluded_expense_ids' => :'Array<Integer>',
        :'export_products_flag' => :'Boolean',
        :'included_product_ids' => :'Array<String>',
        :'excluded_product_ids' => :'Array<String>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'location_id',
        :'export_invoices_flag',
        :'export_expenses_flag',
        :'export_products_flag',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `ConnectWise::ExportAccountingBatchRequest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `ConnectWise::ExportAccountingBatchRequest`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'batch_identifier')
        self.batch_identifier = attributes[:'batch_identifier']
      end

      if attributes.key?(:'gl_interface_identifier')
        self.gl_interface_identifier = attributes[:'gl_interface_identifier']
      end

      if attributes.key?(:'thru_date')
        self.thru_date = attributes[:'thru_date']
      end

      if attributes.key?(:'location_id')
        self.location_id = attributes[:'location_id']
      end

      if attributes.key?(:'summarize_invoices')
        self.summarize_invoices = attributes[:'summarize_invoices']
      end

      if attributes.key?(:'export_invoices_flag')
        self.export_invoices_flag = attributes[:'export_invoices_flag']
      end

      if attributes.key?(:'included_invoice_ids')
        if (value = attributes[:'included_invoice_ids']).is_a?(Array)
          self.included_invoice_ids = value
        end
      end

      if attributes.key?(:'excluded_invoice_ids')
        if (value = attributes[:'excluded_invoice_ids']).is_a?(Array)
          self.excluded_invoice_ids = value
        end
      end

      if attributes.key?(:'export_expenses_flag')
        self.export_expenses_flag = attributes[:'export_expenses_flag']
      end

      if attributes.key?(:'included_expense_ids')
        if (value = attributes[:'included_expense_ids']).is_a?(Array)
          self.included_expense_ids = value
        end
      end

      if attributes.key?(:'excluded_expense_ids')
        if (value = attributes[:'excluded_expense_ids']).is_a?(Array)
          self.excluded_expense_ids = value
        end
      end

      if attributes.key?(:'export_products_flag')
        self.export_products_flag = attributes[:'export_products_flag']
      end

      if attributes.key?(:'included_product_ids')
        if (value = attributes[:'included_product_ids']).is_a?(Array)
          self.included_product_ids = value
        end
      end

      if attributes.key?(:'excluded_product_ids')
        if (value = attributes[:'excluded_product_ids']).is_a?(Array)
          self.excluded_product_ids = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      summarize_invoices_validator = EnumAttributeValidator.new('String', ["Default", "Condensed", "Detailed"])
      return false unless summarize_invoices_validator.valid?(@summarize_invoices)
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] summarize_invoices Object to be assigned
    def summarize_invoices=(summarize_invoices)
      validator = EnumAttributeValidator.new('String', ["Default", "Condensed", "Detailed"])
      unless validator.valid?(summarize_invoices)
        fail ArgumentError, "invalid value for \"summarize_invoices\", must be one of #{validator.allowable_values}."
      end
      @summarize_invoices = summarize_invoices
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          batch_identifier == o.batch_identifier &&
          gl_interface_identifier == o.gl_interface_identifier &&
          thru_date == o.thru_date &&
          location_id == o.location_id &&
          summarize_invoices == o.summarize_invoices &&
          export_invoices_flag == o.export_invoices_flag &&
          included_invoice_ids == o.included_invoice_ids &&
          excluded_invoice_ids == o.excluded_invoice_ids &&
          export_expenses_flag == o.export_expenses_flag &&
          included_expense_ids == o.included_expense_ids &&
          excluded_expense_ids == o.excluded_expense_ids &&
          export_products_flag == o.export_products_flag &&
          included_product_ids == o.included_product_ids &&
          excluded_product_ids == o.excluded_product_ids
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [batch_identifier, gl_interface_identifier, thru_date, location_id, summarize_invoices, export_invoices_flag, included_invoice_ids, excluded_invoice_ids, export_expenses_flag, included_expense_ids, excluded_expense_ids, export_products_flag, included_product_ids, excluded_product_ids].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      self.class.openapi_types.each_pair do |key, type|
        if attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = ConnectWise.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
