=begin
#Connectwise Manage All Endpoints

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2022.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.2.1

=end

require 'date'
require 'time'

module ConnectWise
  class Project
    attr_accessor :billing_method

    attr_accessor :estimated_end

    attr_accessor :estimated_start

    #  Max length: 100;
    attr_accessor :name

    attr_accessor :id

    attr_accessor :_info

    attr_accessor :actual_end

    attr_accessor :actual_hours

    attr_accessor :actual_start

    attr_accessor :agreement

    #  Required On Updates;
    attr_accessor :bill_expenses

    attr_accessor :billing_amount

    #  Max length: 50;
    attr_accessor :billing_attention

    #  Required On Updates;
    attr_accessor :billing_rate_type

    attr_accessor :billing_terms

    #  Required On Updates;
    attr_accessor :bill_products

    attr_accessor :bill_project_after_closed_flag

    #  Required On Updates;
    attr_accessor :bill_time

    attr_accessor :bill_to_company

    attr_accessor :bill_to_contact

    attr_accessor :bill_to_site

    attr_accessor :bill_unapproved_time_and_expense

    attr_accessor :board

    #  Required On Updates;
    attr_accessor :budget_analysis

    attr_accessor :budget_flag

    attr_accessor :budget_hours

    attr_accessor :company

    attr_accessor :contact

    #  Max length: 50;
    attr_accessor :customer_po

    attr_accessor :description

    attr_accessor :currency

    attr_accessor :downpayment

    attr_accessor :percent_complete

    attr_accessor :estimated_expense_revenue

    attr_accessor :estimated_hours

    attr_accessor :estimated_product_revenue

    attr_accessor :estimated_time_revenue

    attr_accessor :expense_approver

    attr_accessor :include_dependencies_flag

    attr_accessor :include_estimates_flag

    attr_accessor :location

    attr_accessor :department

    attr_accessor :manager

    attr_accessor :opportunity

    attr_accessor :project_template_id

    attr_accessor :restrict_down_payment_flag

    attr_accessor :scheduled_end

    attr_accessor :scheduled_hours

    attr_accessor :scheduled_start

    attr_accessor :ship_to_company

    attr_accessor :ship_to_contact

    attr_accessor :ship_to_site

    attr_accessor :site

    attr_accessor :status

    attr_accessor :closed_flag

    attr_accessor :time_approver

    attr_accessor :type

    attr_accessor :do_not_display_in_portal_flag

    attr_accessor :billing_start_date

    attr_accessor :estimated_time_cost

    attr_accessor :estimated_expense_cost

    attr_accessor :estimated_product_cost

    attr_accessor :tax_code

    attr_accessor :company_location

    attr_accessor :custom_fields

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'billing_method' => :'billingMethod',
        :'estimated_end' => :'estimatedEnd',
        :'estimated_start' => :'estimatedStart',
        :'name' => :'name',
        :'id' => :'id',
        :'_info' => :'_info',
        :'actual_end' => :'actualEnd',
        :'actual_hours' => :'actualHours',
        :'actual_start' => :'actualStart',
        :'agreement' => :'agreement',
        :'bill_expenses' => :'billExpenses',
        :'billing_amount' => :'billingAmount',
        :'billing_attention' => :'billingAttention',
        :'billing_rate_type' => :'billingRateType',
        :'billing_terms' => :'billingTerms',
        :'bill_products' => :'billProducts',
        :'bill_project_after_closed_flag' => :'billProjectAfterClosedFlag',
        :'bill_time' => :'billTime',
        :'bill_to_company' => :'billToCompany',
        :'bill_to_contact' => :'billToContact',
        :'bill_to_site' => :'billToSite',
        :'bill_unapproved_time_and_expense' => :'billUnapprovedTimeAndExpense',
        :'board' => :'board',
        :'budget_analysis' => :'budgetAnalysis',
        :'budget_flag' => :'budgetFlag',
        :'budget_hours' => :'budgetHours',
        :'company' => :'company',
        :'contact' => :'contact',
        :'customer_po' => :'customerPO',
        :'description' => :'description',
        :'currency' => :'currency',
        :'downpayment' => :'downpayment',
        :'percent_complete' => :'percentComplete',
        :'estimated_expense_revenue' => :'estimatedExpenseRevenue',
        :'estimated_hours' => :'estimatedHours',
        :'estimated_product_revenue' => :'estimatedProductRevenue',
        :'estimated_time_revenue' => :'estimatedTimeRevenue',
        :'expense_approver' => :'expenseApprover',
        :'include_dependencies_flag' => :'includeDependenciesFlag',
        :'include_estimates_flag' => :'includeEstimatesFlag',
        :'location' => :'location',
        :'department' => :'department',
        :'manager' => :'manager',
        :'opportunity' => :'opportunity',
        :'project_template_id' => :'projectTemplateId',
        :'restrict_down_payment_flag' => :'restrictDownPaymentFlag',
        :'scheduled_end' => :'scheduledEnd',
        :'scheduled_hours' => :'scheduledHours',
        :'scheduled_start' => :'scheduledStart',
        :'ship_to_company' => :'shipToCompany',
        :'ship_to_contact' => :'shipToContact',
        :'ship_to_site' => :'shipToSite',
        :'site' => :'site',
        :'status' => :'status',
        :'closed_flag' => :'closedFlag',
        :'time_approver' => :'timeApprover',
        :'type' => :'type',
        :'do_not_display_in_portal_flag' => :'doNotDisplayInPortalFlag',
        :'billing_start_date' => :'billingStartDate',
        :'estimated_time_cost' => :'estimatedTimeCost',
        :'estimated_expense_cost' => :'estimatedExpenseCost',
        :'estimated_product_cost' => :'estimatedProductCost',
        :'tax_code' => :'taxCode',
        :'company_location' => :'companyLocation',
        :'custom_fields' => :'customFields'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'billing_method' => :'String',
        :'estimated_end' => :'Time',
        :'estimated_start' => :'Time',
        :'name' => :'String',
        :'id' => :'Integer',
        :'_info' => :'Hash<String, String>',
        :'actual_end' => :'Time',
        :'actual_hours' => :'Float',
        :'actual_start' => :'Time',
        :'agreement' => :'AgreementReference',
        :'bill_expenses' => :'String',
        :'billing_amount' => :'Float',
        :'billing_attention' => :'String',
        :'billing_rate_type' => :'String',
        :'billing_terms' => :'BillingTermsReference',
        :'bill_products' => :'String',
        :'bill_project_after_closed_flag' => :'Boolean',
        :'bill_time' => :'String',
        :'bill_to_company' => :'CompanyReference',
        :'bill_to_contact' => :'ContactReference',
        :'bill_to_site' => :'SiteReference',
        :'bill_unapproved_time_and_expense' => :'Boolean',
        :'board' => :'ProjectBoardReference',
        :'budget_analysis' => :'String',
        :'budget_flag' => :'Boolean',
        :'budget_hours' => :'Float',
        :'company' => :'CompanyReference',
        :'contact' => :'ContactReference',
        :'customer_po' => :'String',
        :'description' => :'String',
        :'currency' => :'CurrencyReference',
        :'downpayment' => :'Float',
        :'percent_complete' => :'Float',
        :'estimated_expense_revenue' => :'Float',
        :'estimated_hours' => :'Float',
        :'estimated_product_revenue' => :'Float',
        :'estimated_time_revenue' => :'Float',
        :'expense_approver' => :'MemberReference',
        :'include_dependencies_flag' => :'Boolean',
        :'include_estimates_flag' => :'Boolean',
        :'location' => :'SystemLocationReference',
        :'department' => :'SystemDepartmentReference',
        :'manager' => :'MemberReference',
        :'opportunity' => :'OpportunityReference',
        :'project_template_id' => :'Integer',
        :'restrict_down_payment_flag' => :'Boolean',
        :'scheduled_end' => :'Time',
        :'scheduled_hours' => :'Float',
        :'scheduled_start' => :'Time',
        :'ship_to_company' => :'CompanyReference',
        :'ship_to_contact' => :'ContactReference',
        :'ship_to_site' => :'SiteReference',
        :'site' => :'SiteReference',
        :'status' => :'ProjectStatusReference',
        :'closed_flag' => :'Boolean',
        :'time_approver' => :'MemberReference',
        :'type' => :'ProjectTypeReference',
        :'do_not_display_in_portal_flag' => :'Boolean',
        :'billing_start_date' => :'Time',
        :'estimated_time_cost' => :'Float',
        :'estimated_expense_cost' => :'Float',
        :'estimated_product_cost' => :'Float',
        :'tax_code' => :'TaxCodeReference',
        :'company_location' => :'SystemLocationReference',
        :'custom_fields' => :'Array<CustomFieldValue>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'billing_method',
        :'actual_hours',
        :'bill_expenses',
        :'billing_amount',
        :'billing_rate_type',
        :'bill_products',
        :'bill_project_after_closed_flag',
        :'bill_time',
        :'bill_unapproved_time_and_expense',
        :'budget_analysis',
        :'budget_flag',
        :'budget_hours',
        :'downpayment',
        :'percent_complete',
        :'estimated_expense_revenue',
        :'estimated_hours',
        :'estimated_product_revenue',
        :'estimated_time_revenue',
        :'include_dependencies_flag',
        :'include_estimates_flag',
        :'project_template_id',
        :'restrict_down_payment_flag',
        :'scheduled_hours',
        :'do_not_display_in_portal_flag',
        :'estimated_time_cost',
        :'estimated_expense_cost',
        :'estimated_product_cost',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `ConnectWise::Project` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `ConnectWise::Project`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'billing_method')
        self.billing_method = attributes[:'billing_method']
      end

      if attributes.key?(:'estimated_end')
        self.estimated_end = attributes[:'estimated_end']
      end

      if attributes.key?(:'estimated_start')
        self.estimated_start = attributes[:'estimated_start']
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'_info')
        if (value = attributes[:'_info']).is_a?(Hash)
          self._info = value
        end
      end

      if attributes.key?(:'actual_end')
        self.actual_end = attributes[:'actual_end']
      end

      if attributes.key?(:'actual_hours')
        self.actual_hours = attributes[:'actual_hours']
      end

      if attributes.key?(:'actual_start')
        self.actual_start = attributes[:'actual_start']
      end

      if attributes.key?(:'agreement')
        self.agreement = attributes[:'agreement']
      end

      if attributes.key?(:'bill_expenses')
        self.bill_expenses = attributes[:'bill_expenses']
      end

      if attributes.key?(:'billing_amount')
        self.billing_amount = attributes[:'billing_amount']
      end

      if attributes.key?(:'billing_attention')
        self.billing_attention = attributes[:'billing_attention']
      end

      if attributes.key?(:'billing_rate_type')
        self.billing_rate_type = attributes[:'billing_rate_type']
      end

      if attributes.key?(:'billing_terms')
        self.billing_terms = attributes[:'billing_terms']
      end

      if attributes.key?(:'bill_products')
        self.bill_products = attributes[:'bill_products']
      end

      if attributes.key?(:'bill_project_after_closed_flag')
        self.bill_project_after_closed_flag = attributes[:'bill_project_after_closed_flag']
      end

      if attributes.key?(:'bill_time')
        self.bill_time = attributes[:'bill_time']
      end

      if attributes.key?(:'bill_to_company')
        self.bill_to_company = attributes[:'bill_to_company']
      end

      if attributes.key?(:'bill_to_contact')
        self.bill_to_contact = attributes[:'bill_to_contact']
      end

      if attributes.key?(:'bill_to_site')
        self.bill_to_site = attributes[:'bill_to_site']
      end

      if attributes.key?(:'bill_unapproved_time_and_expense')
        self.bill_unapproved_time_and_expense = attributes[:'bill_unapproved_time_and_expense']
      end

      if attributes.key?(:'board')
        self.board = attributes[:'board']
      end

      if attributes.key?(:'budget_analysis')
        self.budget_analysis = attributes[:'budget_analysis']
      end

      if attributes.key?(:'budget_flag')
        self.budget_flag = attributes[:'budget_flag']
      end

      if attributes.key?(:'budget_hours')
        self.budget_hours = attributes[:'budget_hours']
      end

      if attributes.key?(:'company')
        self.company = attributes[:'company']
      end

      if attributes.key?(:'contact')
        self.contact = attributes[:'contact']
      end

      if attributes.key?(:'customer_po')
        self.customer_po = attributes[:'customer_po']
      end

      if attributes.key?(:'description')
        self.description = attributes[:'description']
      end

      if attributes.key?(:'currency')
        self.currency = attributes[:'currency']
      end

      if attributes.key?(:'downpayment')
        self.downpayment = attributes[:'downpayment']
      end

      if attributes.key?(:'percent_complete')
        self.percent_complete = attributes[:'percent_complete']
      end

      if attributes.key?(:'estimated_expense_revenue')
        self.estimated_expense_revenue = attributes[:'estimated_expense_revenue']
      end

      if attributes.key?(:'estimated_hours')
        self.estimated_hours = attributes[:'estimated_hours']
      end

      if attributes.key?(:'estimated_product_revenue')
        self.estimated_product_revenue = attributes[:'estimated_product_revenue']
      end

      if attributes.key?(:'estimated_time_revenue')
        self.estimated_time_revenue = attributes[:'estimated_time_revenue']
      end

      if attributes.key?(:'expense_approver')
        self.expense_approver = attributes[:'expense_approver']
      end

      if attributes.key?(:'include_dependencies_flag')
        self.include_dependencies_flag = attributes[:'include_dependencies_flag']
      end

      if attributes.key?(:'include_estimates_flag')
        self.include_estimates_flag = attributes[:'include_estimates_flag']
      end

      if attributes.key?(:'location')
        self.location = attributes[:'location']
      end

      if attributes.key?(:'department')
        self.department = attributes[:'department']
      end

      if attributes.key?(:'manager')
        self.manager = attributes[:'manager']
      end

      if attributes.key?(:'opportunity')
        self.opportunity = attributes[:'opportunity']
      end

      if attributes.key?(:'project_template_id')
        self.project_template_id = attributes[:'project_template_id']
      end

      if attributes.key?(:'restrict_down_payment_flag')
        self.restrict_down_payment_flag = attributes[:'restrict_down_payment_flag']
      end

      if attributes.key?(:'scheduled_end')
        self.scheduled_end = attributes[:'scheduled_end']
      end

      if attributes.key?(:'scheduled_hours')
        self.scheduled_hours = attributes[:'scheduled_hours']
      end

      if attributes.key?(:'scheduled_start')
        self.scheduled_start = attributes[:'scheduled_start']
      end

      if attributes.key?(:'ship_to_company')
        self.ship_to_company = attributes[:'ship_to_company']
      end

      if attributes.key?(:'ship_to_contact')
        self.ship_to_contact = attributes[:'ship_to_contact']
      end

      if attributes.key?(:'ship_to_site')
        self.ship_to_site = attributes[:'ship_to_site']
      end

      if attributes.key?(:'site')
        self.site = attributes[:'site']
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      end

      if attributes.key?(:'closed_flag')
        self.closed_flag = attributes[:'closed_flag']
      end

      if attributes.key?(:'time_approver')
        self.time_approver = attributes[:'time_approver']
      end

      if attributes.key?(:'type')
        self.type = attributes[:'type']
      end

      if attributes.key?(:'do_not_display_in_portal_flag')
        self.do_not_display_in_portal_flag = attributes[:'do_not_display_in_portal_flag']
      end

      if attributes.key?(:'billing_start_date')
        self.billing_start_date = attributes[:'billing_start_date']
      end

      if attributes.key?(:'estimated_time_cost')
        self.estimated_time_cost = attributes[:'estimated_time_cost']
      end

      if attributes.key?(:'estimated_expense_cost')
        self.estimated_expense_cost = attributes[:'estimated_expense_cost']
      end

      if attributes.key?(:'estimated_product_cost')
        self.estimated_product_cost = attributes[:'estimated_product_cost']
      end

      if attributes.key?(:'tax_code')
        self.tax_code = attributes[:'tax_code']
      end

      if attributes.key?(:'company_location')
        self.company_location = attributes[:'company_location']
      end

      if attributes.key?(:'custom_fields')
        if (value = attributes[:'custom_fields']).is_a?(Array)
          self.custom_fields = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @estimated_end.nil?
        invalid_properties.push('invalid value for "estimated_end", estimated_end cannot be nil.')
      end

      if @estimated_start.nil?
        invalid_properties.push('invalid value for "estimated_start", estimated_start cannot be nil.')
      end

      if @name.nil?
        invalid_properties.push('invalid value for "name", name cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      billing_method_validator = EnumAttributeValidator.new('String', ["ActualRates", "FixedFee", "NotToExceed", "OverrideRate"])
      return false unless billing_method_validator.valid?(@billing_method)
      return false if @estimated_end.nil?
      return false if @estimated_start.nil?
      return false if @name.nil?
      bill_expenses_validator = EnumAttributeValidator.new('String', ["Billable", "DoNotBill", "NoCharge", "NoDefault"])
      return false unless bill_expenses_validator.valid?(@bill_expenses)
      billing_rate_type_validator = EnumAttributeValidator.new('String', ["StaffMember", "WorkRole"])
      return false unless billing_rate_type_validator.valid?(@billing_rate_type)
      bill_products_validator = EnumAttributeValidator.new('String', ["Billable", "DoNotBill", "NoCharge", "NoDefault"])
      return false unless bill_products_validator.valid?(@bill_products)
      bill_time_validator = EnumAttributeValidator.new('String', ["Billable", "DoNotBill", "NoCharge", "NoDefault"])
      return false unless bill_time_validator.valid?(@bill_time)
      budget_analysis_validator = EnumAttributeValidator.new('String', ["ActualHours", "BillableHours"])
      return false unless budget_analysis_validator.valid?(@budget_analysis)
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] billing_method Object to be assigned
    def billing_method=(billing_method)
      validator = EnumAttributeValidator.new('String', ["ActualRates", "FixedFee", "NotToExceed", "OverrideRate"])
      unless validator.valid?(billing_method)
        fail ArgumentError, "invalid value for \"billing_method\", must be one of #{validator.allowable_values}."
      end
      @billing_method = billing_method
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] bill_expenses Object to be assigned
    def bill_expenses=(bill_expenses)
      validator = EnumAttributeValidator.new('String', ["Billable", "DoNotBill", "NoCharge", "NoDefault"])
      unless validator.valid?(bill_expenses)
        fail ArgumentError, "invalid value for \"bill_expenses\", must be one of #{validator.allowable_values}."
      end
      @bill_expenses = bill_expenses
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] billing_rate_type Object to be assigned
    def billing_rate_type=(billing_rate_type)
      validator = EnumAttributeValidator.new('String', ["StaffMember", "WorkRole"])
      unless validator.valid?(billing_rate_type)
        fail ArgumentError, "invalid value for \"billing_rate_type\", must be one of #{validator.allowable_values}."
      end
      @billing_rate_type = billing_rate_type
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] bill_products Object to be assigned
    def bill_products=(bill_products)
      validator = EnumAttributeValidator.new('String', ["Billable", "DoNotBill", "NoCharge", "NoDefault"])
      unless validator.valid?(bill_products)
        fail ArgumentError, "invalid value for \"bill_products\", must be one of #{validator.allowable_values}."
      end
      @bill_products = bill_products
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] bill_time Object to be assigned
    def bill_time=(bill_time)
      validator = EnumAttributeValidator.new('String', ["Billable", "DoNotBill", "NoCharge", "NoDefault"])
      unless validator.valid?(bill_time)
        fail ArgumentError, "invalid value for \"bill_time\", must be one of #{validator.allowable_values}."
      end
      @bill_time = bill_time
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] budget_analysis Object to be assigned
    def budget_analysis=(budget_analysis)
      validator = EnumAttributeValidator.new('String', ["ActualHours", "BillableHours"])
      unless validator.valid?(budget_analysis)
        fail ArgumentError, "invalid value for \"budget_analysis\", must be one of #{validator.allowable_values}."
      end
      @budget_analysis = budget_analysis
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          billing_method == o.billing_method &&
          estimated_end == o.estimated_end &&
          estimated_start == o.estimated_start &&
          name == o.name &&
          id == o.id &&
          _info == o._info &&
          actual_end == o.actual_end &&
          actual_hours == o.actual_hours &&
          actual_start == o.actual_start &&
          agreement == o.agreement &&
          bill_expenses == o.bill_expenses &&
          billing_amount == o.billing_amount &&
          billing_attention == o.billing_attention &&
          billing_rate_type == o.billing_rate_type &&
          billing_terms == o.billing_terms &&
          bill_products == o.bill_products &&
          bill_project_after_closed_flag == o.bill_project_after_closed_flag &&
          bill_time == o.bill_time &&
          bill_to_company == o.bill_to_company &&
          bill_to_contact == o.bill_to_contact &&
          bill_to_site == o.bill_to_site &&
          bill_unapproved_time_and_expense == o.bill_unapproved_time_and_expense &&
          board == o.board &&
          budget_analysis == o.budget_analysis &&
          budget_flag == o.budget_flag &&
          budget_hours == o.budget_hours &&
          company == o.company &&
          contact == o.contact &&
          customer_po == o.customer_po &&
          description == o.description &&
          currency == o.currency &&
          downpayment == o.downpayment &&
          percent_complete == o.percent_complete &&
          estimated_expense_revenue == o.estimated_expense_revenue &&
          estimated_hours == o.estimated_hours &&
          estimated_product_revenue == o.estimated_product_revenue &&
          estimated_time_revenue == o.estimated_time_revenue &&
          expense_approver == o.expense_approver &&
          include_dependencies_flag == o.include_dependencies_flag &&
          include_estimates_flag == o.include_estimates_flag &&
          location == o.location &&
          department == o.department &&
          manager == o.manager &&
          opportunity == o.opportunity &&
          project_template_id == o.project_template_id &&
          restrict_down_payment_flag == o.restrict_down_payment_flag &&
          scheduled_end == o.scheduled_end &&
          scheduled_hours == o.scheduled_hours &&
          scheduled_start == o.scheduled_start &&
          ship_to_company == o.ship_to_company &&
          ship_to_contact == o.ship_to_contact &&
          ship_to_site == o.ship_to_site &&
          site == o.site &&
          status == o.status &&
          closed_flag == o.closed_flag &&
          time_approver == o.time_approver &&
          type == o.type &&
          do_not_display_in_portal_flag == o.do_not_display_in_portal_flag &&
          billing_start_date == o.billing_start_date &&
          estimated_time_cost == o.estimated_time_cost &&
          estimated_expense_cost == o.estimated_expense_cost &&
          estimated_product_cost == o.estimated_product_cost &&
          tax_code == o.tax_code &&
          company_location == o.company_location &&
          custom_fields == o.custom_fields
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [billing_method, estimated_end, estimated_start, name, id, _info, actual_end, actual_hours, actual_start, agreement, bill_expenses, billing_amount, billing_attention, billing_rate_type, billing_terms, bill_products, bill_project_after_closed_flag, bill_time, bill_to_company, bill_to_contact, bill_to_site, bill_unapproved_time_and_expense, board, budget_analysis, budget_flag, budget_hours, company, contact, customer_po, description, currency, downpayment, percent_complete, estimated_expense_revenue, estimated_hours, estimated_product_revenue, estimated_time_revenue, expense_approver, include_dependencies_flag, include_estimates_flag, location, department, manager, opportunity, project_template_id, restrict_down_payment_flag, scheduled_end, scheduled_hours, scheduled_start, ship_to_company, ship_to_contact, ship_to_site, site, status, closed_flag, time_approver, type, do_not_display_in_portal_flag, billing_start_date, estimated_time_cost, estimated_expense_cost, estimated_product_cost, tax_code, company_location, custom_fields].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      self.class.openapi_types.each_pair do |key, type|
        if attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = ConnectWise.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
