# #Connectwise Manage All Endpoints
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: 2022.1
#
# Generated by: https://openapi-generator.tech
# OpenAPI Generator version: 6.2.1
#

require 'date'
require 'time'

module ConnectWise
  class TimeEntry
    attr_accessor :time_start, :id, :company, :member, :location_id, :business_unit_id, :work_type, :work_role, :agreement, :time_end, :hours_deduct, :actual_hours, :notes, :internal_notes, :add_to_detail_description_flag, :add_to_internal_analysis_flag, :add_to_resolution_flag, :hours_billed, :invoice_hours, :entered_by, :date_entered, :invoice, :mobile_guid, :overage_rate, :agreement_hours, :agreement_amount, :time_sheet, :status, :ticket, :project, :phase, :_info, :custom_fields

    # If chargeToId is not specified, we asume you enter time against the company specified
    attr_accessor :charge_to_id

    # If chargeToId is not specified, we asume you enter time against the company specified
    attr_accessor :charge_to_type

    #  Required On Updates;
    attr_accessor :billable_option

    # This is an action flag. To update this value use the /service/tickets endpoint automaticEmailResourceFlag field
    attr_accessor :email_resource_flag

    # This is an action flag. To update this value use the /service/tickets endpoint automaticEmailContactFlag field
    attr_accessor :email_contact_flag

    # This is an action flag. To update this value use the /service/tickets endpoint automaticEmailCcFlag field
    attr_accessor :email_cc_flag

    # To update this value use the /service/tickets endpoint automaticEmailCc field
    attr_accessor :email_cc

    # This field may only be Updated, it is defaulted on Create
    attr_accessor :hourly_rate

    class EnumAttributeValidator
      attr_reader :datatype, :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        time_start: :timeStart,
        id: :id,
        company: :company,
        charge_to_id: :chargeToId,
        charge_to_type: :chargeToType,
        member: :member,
        location_id: :locationId,
        business_unit_id: :businessUnitId,
        work_type: :workType,
        work_role: :workRole,
        agreement: :agreement,
        time_end: :timeEnd,
        hours_deduct: :hoursDeduct,
        actual_hours: :actualHours,
        billable_option: :billableOption,
        notes: :notes,
        internal_notes: :internalNotes,
        add_to_detail_description_flag: :addToDetailDescriptionFlag,
        add_to_internal_analysis_flag: :addToInternalAnalysisFlag,
        add_to_resolution_flag: :addToResolutionFlag,
        email_resource_flag: :emailResourceFlag,
        email_contact_flag: :emailContactFlag,
        email_cc_flag: :emailCcFlag,
        email_cc: :emailCc,
        hours_billed: :hoursBilled,
        invoice_hours: :invoiceHours,
        entered_by: :enteredBy,
        date_entered: :dateEntered,
        invoice: :invoice,
        mobile_guid: :mobileGuid,
        hourly_rate: :hourlyRate,
        overage_rate: :overageRate,
        agreement_hours: :agreementHours,
        agreement_amount: :agreementAmount,
        time_sheet: :timeSheet,
        status: :status,
        ticket: :ticket,
        project: :project,
        phase: :phase,
        _info: :_info,
        custom_fields: :customFields
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        time_start: :Time,
        id: :Integer,
        company: :CompanyReference,
        charge_to_id: :Integer,
        charge_to_type: :String,
        member: :MemberReference,
        location_id: :Integer,
        business_unit_id: :Integer,
        work_type: :WorkTypeReference,
        work_role: :WorkRoleReference,
        agreement: :AgreementReference,
        time_end: :Time,
        hours_deduct: :Float,
        actual_hours: :Float,
        billable_option: :String,
        notes: :String,
        internal_notes: :String,
        add_to_detail_description_flag: :Boolean,
        add_to_internal_analysis_flag: :Boolean,
        add_to_resolution_flag: :Boolean,
        email_resource_flag: :Boolean,
        email_contact_flag: :Boolean,
        email_cc_flag: :Boolean,
        email_cc: :String,
        hours_billed: :Float,
        invoice_hours: :Float,
        entered_by: :String,
        date_entered: :Time,
        invoice: :InvoiceReference,
        mobile_guid: :String,
        hourly_rate: :Float,
        overage_rate: :Float,
        agreement_hours: :Float,
        agreement_amount: :Float,
        time_sheet: :TimeSheetReference,
        status: :String,
        ticket: :TicketReference,
        project: :ProjectReference,
        phase: :ProjectPhaseReference,
        _info: :'Hash<String, String>',
        custom_fields: :'Array<CustomFieldValue>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new(%i[
                charge_to_id
                charge_to_type
                location_id
                business_unit_id
                hours_deduct
                actual_hours
                billable_option
                add_to_detail_description_flag
                add_to_internal_analysis_flag
                add_to_resolution_flag
                email_resource_flag
                email_contact_flag
                email_cc_flag
                hours_billed
                invoice_hours
                mobile_guid
                hourly_rate
                overage_rate
                agreement_hours
                agreement_amount
                status
              ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      raise ArgumentError, 'The input argument (attributes) must be a hash in `ConnectWise::TimeEntry` initialize method' unless attributes.is_a?(Hash)

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) do |(k, v), h|
        raise ArgumentError, "`#{k}` is not a valid attribute in `ConnectWise::TimeEntry`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect unless self.class.attribute_map.key?(k.to_sym)

        h[k.to_sym] = v
      end

      self.time_start = attributes[:time_start] if attributes.key?(:time_start)

      self.id = attributes[:id] if attributes.key?(:id)

      self.company = attributes[:company] if attributes.key?(:company)

      self.charge_to_id = attributes[:charge_to_id] if attributes.key?(:charge_to_id)

      self.charge_to_type = attributes[:charge_to_type] if attributes.key?(:charge_to_type)

      self.member = attributes[:member] if attributes.key?(:member)

      self.location_id = attributes[:location_id] if attributes.key?(:location_id)

      self.business_unit_id = attributes[:business_unit_id] if attributes.key?(:business_unit_id)

      self.work_type = attributes[:work_type] if attributes.key?(:work_type)

      self.work_role = attributes[:work_role] if attributes.key?(:work_role)

      self.agreement = attributes[:agreement] if attributes.key?(:agreement)

      self.time_end = attributes[:time_end] if attributes.key?(:time_end)

      self.hours_deduct = attributes[:hours_deduct] if attributes.key?(:hours_deduct)

      self.actual_hours = attributes[:actual_hours] if attributes.key?(:actual_hours)

      self.billable_option = attributes[:billable_option] if attributes.key?(:billable_option)

      self.notes = attributes[:notes] if attributes.key?(:notes)

      self.internal_notes = attributes[:internal_notes] if attributes.key?(:internal_notes)

      self.add_to_detail_description_flag = attributes[:add_to_detail_description_flag] if attributes.key?(:add_to_detail_description_flag)

      self.add_to_internal_analysis_flag = attributes[:add_to_internal_analysis_flag] if attributes.key?(:add_to_internal_analysis_flag)

      self.add_to_resolution_flag = attributes[:add_to_resolution_flag] if attributes.key?(:add_to_resolution_flag)

      self.email_resource_flag = attributes[:email_resource_flag] if attributes.key?(:email_resource_flag)

      self.email_contact_flag = attributes[:email_contact_flag] if attributes.key?(:email_contact_flag)

      self.email_cc_flag = attributes[:email_cc_flag] if attributes.key?(:email_cc_flag)

      self.email_cc = attributes[:email_cc] if attributes.key?(:email_cc)

      self.hours_billed = attributes[:hours_billed] if attributes.key?(:hours_billed)

      self.invoice_hours = attributes[:invoice_hours] if attributes.key?(:invoice_hours)

      self.entered_by = attributes[:entered_by] if attributes.key?(:entered_by)

      self.date_entered = attributes[:date_entered] if attributes.key?(:date_entered)

      self.invoice = attributes[:invoice] if attributes.key?(:invoice)

      self.mobile_guid = attributes[:mobile_guid] if attributes.key?(:mobile_guid)

      self.hourly_rate = attributes[:hourly_rate] if attributes.key?(:hourly_rate)

      self.overage_rate = attributes[:overage_rate] if attributes.key?(:overage_rate)

      self.agreement_hours = attributes[:agreement_hours] if attributes.key?(:agreement_hours)

      self.agreement_amount = attributes[:agreement_amount] if attributes.key?(:agreement_amount)

      self.time_sheet = attributes[:time_sheet] if attributes.key?(:time_sheet)

      self.status = attributes[:status] if attributes.key?(:status)

      self.ticket = attributes[:ticket] if attributes.key?(:ticket)

      self.project = attributes[:project] if attributes.key?(:project)

      self.phase = attributes[:phase] if attributes.key?(:phase)

      if attributes.key?(:_info) && (value = attributes[:_info]).is_a?(Hash)
        self._info = value
      end

      return unless attributes.key?(:custom_fields)
      return unless (value = attributes[:custom_fields]).is_a?(Array)

      self.custom_fields = value
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = []
      invalid_properties.push('invalid value for "time_start", time_start cannot be nil.') if @time_start.nil?

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @time_start.nil?

      charge_to_type_validator = EnumAttributeValidator.new('String', %w[ServiceTicket ProjectTicket ChargeCode Activity])
      return false unless charge_to_type_validator.valid?(@charge_to_type)

      billable_option_validator = EnumAttributeValidator.new('String', %w[Billable DoNotBill NoCharge NoDefault])
      return false unless billable_option_validator.valid?(@billable_option)

      status_validator = EnumAttributeValidator.new('String', %w[Open Rejected PendingApproval ErrorsCorrected PendingProjectApproval ApprovedByTierOne RejectBySecondTier ApprovedByTierTwo ReadyToBill Billed WrittenOff BilledAgreement])
      return false unless status_validator.valid?(@status)

      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] charge_to_type Object to be assigned
    def charge_to_type=(charge_to_type)
      validator = EnumAttributeValidator.new('String', %w[ServiceTicket ProjectTicket ChargeCode Activity])
      raise ArgumentError, "invalid value for \"charge_to_type\", must be one of #{validator.allowable_values}." unless validator.valid?(charge_to_type)

      @charge_to_type = charge_to_type
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] billable_option Object to be assigned
    def billable_option=(billable_option)
      validator = EnumAttributeValidator.new('String', %w[Billable DoNotBill NoCharge NoDefault])
      raise ArgumentError, "invalid value for \"billable_option\", must be one of #{validator.allowable_values}." unless validator.valid?(billable_option)

      @billable_option = billable_option
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] status Object to be assigned
    def status=(status)
      validator = EnumAttributeValidator.new('String', %w[Open Rejected PendingApproval ErrorsCorrected PendingProjectApproval ApprovedByTierOne RejectBySecondTier ApprovedByTierTwo ReadyToBill Billed WrittenOff BilledAgreement])
      raise ArgumentError, "invalid value for \"status\", must be one of #{validator.allowable_values}." unless validator.valid?(status)

      @status = status
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(other)
      return true if equal?(other)

      self.class == other.class &&
        time_start == other.time_start &&
        id == other.id &&
        company == other.company &&
        charge_to_id == other.charge_to_id &&
        charge_to_type == other.charge_to_type &&
        member == other.member &&
        location_id == other.location_id &&
        business_unit_id == other.business_unit_id &&
        work_type == other.work_type &&
        work_role == other.work_role &&
        agreement == other.agreement &&
        time_end == other.time_end &&
        hours_deduct == other.hours_deduct &&
        actual_hours == other.actual_hours &&
        billable_option == other.billable_option &&
        notes == other.notes &&
        internal_notes == other.internal_notes &&
        add_to_detail_description_flag == other.add_to_detail_description_flag &&
        add_to_internal_analysis_flag == other.add_to_internal_analysis_flag &&
        add_to_resolution_flag == other.add_to_resolution_flag &&
        email_resource_flag == other.email_resource_flag &&
        email_contact_flag == other.email_contact_flag &&
        email_cc_flag == other.email_cc_flag &&
        email_cc == other.email_cc &&
        hours_billed == other.hours_billed &&
        invoice_hours == other.invoice_hours &&
        entered_by == other.entered_by &&
        date_entered == other.date_entered &&
        invoice == other.invoice &&
        mobile_guid == other.mobile_guid &&
        hourly_rate == other.hourly_rate &&
        overage_rate == other.overage_rate &&
        agreement_hours == other.agreement_hours &&
        agreement_amount == other.agreement_amount &&
        time_sheet == other.time_sheet &&
        status == other.status &&
        ticket == other.ticket &&
        project == other.project &&
        phase == other.phase &&
        _info == other._info &&
        custom_fields == other.custom_fields
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(other)
      self == other
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [time_start, id, company, charge_to_id, charge_to_type, member, location_id, business_unit_id, work_type, work_role, agreement, time_end, hours_deduct, actual_hours, billable_option, notes, internal_notes, add_to_detail_description_flag, add_to_internal_analysis_flag, add_to_resolution_flag, email_resource_flag, email_contact_flag, email_cc_flag, email_cc, hours_billed, invoice_hours, entered_by, date_entered, invoice, mobile_guid, hourly_rate, overage_rate, agreement_hours, agreement_amount, time_sheet, status, ticket, project, phase, _info, custom_fields].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)

      attributes = attributes.transform_keys(&:to_sym)
      self.class.openapi_types.each_pair do |key, type|
        if attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          send("#{key}=", nil)
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize(::Regexp.last_match(1), v) }) if attributes[self.class.attribute_map[key]].is_a?(Array)
        elsif !attributes[self.class.attribute_map[key]].nil?
          send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = ConnectWise.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end
  end
end
