require:
  - rubocop-rake

AllCops:
  Exclude:
    - '**/templates/**/*'
    - '**/vendor/**/*'
  NewCops: enable
  TargetRubyVersion: 2.7

Layout/AssignmentIndentation:
  Enabled: false

Layout/LineContinuationLeadingSpace:
  Enabled: false

Layout/LineLength:
  Enabled: false

Lint/DuplicateMethods:
  Enabled: false

Lint/UnderscorePrefixedVariableName:
  Enabled: false

Lint/UselessAssignment:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Security/CompoundHash:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/GlobalStdStream:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/StringConcatenation:
  Enabled: false
