# #Connectwise Manage All Endpoints
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: 2022.1
#
# Generated by: https://openapi-generator.tech
# OpenAPI Generator version: 6.2.1
#

require 'spec_helper'
require 'json'

# Unit tests for ConnectWise::AccountingUnpostedProcurementTaxableLevelsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AccountingUnpostedProcurementTaxableLevelsApi' do
  before do
    # run before each test
    @api_instance = ConnectWise::AccountingUnpostedProcurementTaxableLevelsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AccountingUnpostedProcurementTaxableLevelsApi' do
    it 'should create an instance of AccountingUnpostedProcurementTaxableLevelsApi' do
      expect(@api_instance).to be_instance_of(ConnectWise::AccountingUnpostedProcurementTaxableLevelsApi)
    end
  end

  # unit tests for get_finance_accounting_unpostedprocurement_by_parent_id_taxable_levels
  # Get List of UnpostedProcurementTaxableLevel
  # @param parent_id unpostedprocurementId
  # @param client_id
  # @param [Hash] opts the optional parameters
  # @option opts [String] :conditions
  # @option opts [String] :child_conditions
  # @option opts [String] :custom_field_conditions
  # @option opts [String] :order_by
  # @option opts [String] :fields
  # @option opts [Integer] :page
  # @option opts [Integer] :page_size
  # @option opts [Integer] :page_id
  # @return [Array<UnpostedProcurementTaxableLevel>]
  describe 'get_finance_accounting_unpostedprocurement_by_parent_id_taxable_levels test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_finance_accounting_unpostedprocurement_by_parent_id_taxable_levels_by_id
  # Get UnpostedProcurementTaxableLevel
  # @param id taxableLevelId
  # @param parent_id unpostedprocurementId
  # @param client_id
  # @param [Hash] opts the optional parameters
  # @option opts [String] :conditions
  # @option opts [String] :child_conditions
  # @option opts [String] :custom_field_conditions
  # @option opts [String] :order_by
  # @option opts [String] :fields
  # @option opts [Integer] :page
  # @option opts [Integer] :page_size
  # @option opts [Integer] :page_id
  # @return [UnpostedProcurementTaxableLevel]
  describe 'get_finance_accounting_unpostedprocurement_by_parent_id_taxable_levels_by_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_finance_accounting_unpostedprocurement_by_parent_id_taxable_levels_count
  # Get Count of UnpostedProcurementTaxableLevel
  # @param parent_id unpostedprocurementId
  # @param client_id
  # @param [Hash] opts the optional parameters
  # @option opts [String] :conditions
  # @option opts [String] :child_conditions
  # @option opts [String] :custom_field_conditions
  # @option opts [String] :order_by
  # @option opts [String] :fields
  # @option opts [Integer] :page
  # @option opts [Integer] :page_size
  # @option opts [Integer] :page_id
  # @return [Count]
  describe 'get_finance_accounting_unpostedprocurement_by_parent_id_taxable_levels_count test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end
end
