# #Connectwise Manage Public Endpoints
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: 2025.1
#
# Generated by: https://openapi-generator.tech
# Generator version: 7.12.0
#

require 'spec_helper'
require 'json'

# Unit tests for ConnectWise::ContactCommunicationsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ContactCommunicationsApi' do
  before do
    # run before each test
    @api_instance = ConnectWise::ContactCommunicationsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ContactCommunicationsApi' do
    it 'should create an instance of ContactCommunicationsApi' do
      expect(@api_instance).to be_instance_of(ConnectWise::ContactCommunicationsApi)
    end
  end

  # unit tests for delete_company_contacts_by_parent_id_communications_by_id
  # Delete ContactCommunication
  # @param id communicationId
  # @param parent_id contactId
  # @param client_id
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_company_contacts_by_parent_id_communications_by_id test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_company_contacts_by_parent_id_communications
  # Get List of ContactCommunication
  # @param parent_id contactId
  # @param client_id
  # @param [Hash] opts the optional parameters
  # @option opts [String] :conditions
  # @option opts [String] :child_conditions
  # @option opts [String] :custom_field_conditions
  # @option opts [String] :order_by
  # @option opts [String] :fields
  # @option opts [Integer] :page
  # @option opts [Integer] :page_size
  # @option opts [Integer] :page_id
  # @return [Array<ContactCommunication>]
  describe 'get_company_contacts_by_parent_id_communications test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_company_contacts_by_parent_id_communications_by_id
  # Get ContactCommunication
  # @param id communicationId
  # @param parent_id contactId
  # @param client_id
  # @param [Hash] opts the optional parameters
  # @option opts [String] :conditions
  # @option opts [String] :child_conditions
  # @option opts [String] :custom_field_conditions
  # @option opts [String] :order_by
  # @option opts [String] :fields
  # @option opts [Integer] :page
  # @option opts [Integer] :page_size
  # @option opts [Integer] :page_id
  # @return [ContactCommunication]
  describe 'get_company_contacts_by_parent_id_communications_by_id test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_company_contacts_by_parent_id_communications_count
  # Get Count of ContactCommunication
  # @param parent_id contactId
  # @param client_id
  # @param [Hash] opts the optional parameters
  # @option opts [String] :conditions
  # @option opts [String] :child_conditions
  # @option opts [String] :custom_field_conditions
  # @option opts [String] :order_by
  # @option opts [String] :fields
  # @option opts [Integer] :page
  # @option opts [Integer] :page_size
  # @option opts [Integer] :page_id
  # @return [Count]
  describe 'get_company_contacts_by_parent_id_communications_count test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for patch_company_contacts_by_parent_id_communications_by_id
  # Patch ContactCommunication
  # @param id communicationId
  # @param parent_id contactId
  # @param client_id
  # @param patch_operation List of PatchOperation
  # @param [Hash] opts the optional parameters
  # @return [ContactCommunication]
  describe 'patch_company_contacts_by_parent_id_communications_by_id test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for post_company_contacts_by_parent_id_communications
  # Post ContactCommunication
  # @param parent_id contactId
  # @param client_id
  # @param contact_communication contactCommunication
  # @param [Hash] opts the optional parameters
  # @return [ContactCommunication]
  describe 'post_company_contacts_by_parent_id_communications test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for put_company_contacts_by_parent_id_communications_by_id
  # Put ContactCommunication
  # @param id communicationId
  # @param parent_id contactId
  # @param client_id
  # @param contact_communication contactCommunication
  # @param [Hash] opts the optional parameters
  # @return [ContactCommunication]
  describe 'put_company_contacts_by_parent_id_communications_by_id test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end
end
