=begin
#Connectwise Manage All Endpoints

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2022.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.2.1

=end

require 'spec_helper'
require 'json'

# Unit tests for ConnectWise::ServiceSurveyQuestionsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ServiceSurveyQuestionsApi' do
  before do
    # run before each test
    @api_instance = ConnectWise::ServiceSurveyQuestionsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ServiceSurveyQuestionsApi' do
    it 'should create an instance of ServiceSurveyQuestionsApi' do
      expect(@api_instance).to be_instance_of(ConnectWise::ServiceSurveyQuestionsApi)
    end
  end

  # unit tests for delete_service_surveys_by_parent_id_questions_by_id
  # Delete ServiceSurveyQuestion
  # @param id questionId
  # @param parent_id surveyId
  # @param client_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_service_surveys_by_parent_id_questions_by_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_service_surveys_by_parent_id_questions
  # Get List of ServiceSurveyQuestion
  # @param parent_id surveyId
  # @param client_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :conditions 
  # @option opts [String] :child_conditions 
  # @option opts [String] :custom_field_conditions 
  # @option opts [String] :order_by 
  # @option opts [String] :fields 
  # @option opts [Integer] :page 
  # @option opts [Integer] :page_size 
  # @option opts [Integer] :page_id 
  # @return [Array<ServiceSurveyQuestion>]
  describe 'get_service_surveys_by_parent_id_questions test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_service_surveys_by_parent_id_questions_by_id
  # Get ServiceSurveyQuestion
  # @param id questionId
  # @param parent_id surveyId
  # @param client_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :conditions 
  # @option opts [String] :child_conditions 
  # @option opts [String] :custom_field_conditions 
  # @option opts [String] :order_by 
  # @option opts [String] :fields 
  # @option opts [Integer] :page 
  # @option opts [Integer] :page_size 
  # @option opts [Integer] :page_id 
  # @return [ServiceSurveyQuestion]
  describe 'get_service_surveys_by_parent_id_questions_by_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_service_surveys_by_parent_id_questions_count
  # Get Count of ServiceSurveyQuestion
  # @param parent_id surveyId
  # @param client_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :conditions 
  # @option opts [String] :child_conditions 
  # @option opts [String] :custom_field_conditions 
  # @option opts [String] :order_by 
  # @option opts [String] :fields 
  # @option opts [Integer] :page 
  # @option opts [Integer] :page_size 
  # @option opts [Integer] :page_id 
  # @return [Count]
  describe 'get_service_surveys_by_parent_id_questions_count test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for patch_service_surveys_by_parent_id_questions_by_id
  # Patch ServiceSurveyQuestion
  # @param id questionId
  # @param parent_id surveyId
  # @param client_id 
  # @param patch_operation List of PatchOperation
  # @param [Hash] opts the optional parameters
  # @return [ServiceSurveyQuestion]
  describe 'patch_service_surveys_by_parent_id_questions_by_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_service_surveys_by_parent_id_questions
  # Post ServiceSurveyQuestion
  # @param parent_id surveyId
  # @param client_id 
  # @param service_survey_question serviceSurveyQuestion
  # @param [Hash] opts the optional parameters
  # @return [ServiceSurveyQuestion]
  describe 'post_service_surveys_by_parent_id_questions test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_service_surveys_by_parent_id_questions_by_id_copy
  # Post ServiceSurveyQuestion
  # @param id questionId
  # @param parent_id surveyId
  # @param client_id 
  # @param [Hash] opts the optional parameters
  # @return [ServiceSurveyQuestion]
  describe 'post_service_surveys_by_parent_id_questions_by_id_copy test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for put_service_surveys_by_parent_id_questions_by_id
  # Put ServiceSurveyQuestion
  # @param id questionId
  # @param parent_id surveyId
  # @param client_id 
  # @param service_survey_question serviceSurveyQuestion
  # @param [Hash] opts the optional parameters
  # @return [ServiceSurveyQuestion]
  describe 'put_service_surveys_by_parent_id_questions_by_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
