# #Connectwise Manage All Endpoints
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: 2022.1
#
# Generated by: https://openapi-generator.tech
# OpenAPI Generator version: 6.2.1
#

require 'spec_helper'
require 'json'

# Unit tests for ConnectWise::TaxCodeExpenseTypeExemptionsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'TaxCodeExpenseTypeExemptionsApi' do
  before do
    # run before each test
    @api_instance = ConnectWise::TaxCodeExpenseTypeExemptionsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TaxCodeExpenseTypeExemptionsApi' do
    it 'should create an instance of TaxCodeExpenseTypeExemptionsApi' do
      expect(@api_instance).to be_instance_of(ConnectWise::TaxCodeExpenseTypeExemptionsApi)
    end
  end

  # unit tests for delete_finance_tax_codes_by_parent_id_expense_type_exemptions_by_id
  # Delete ExpenseTypeExemption
  # @param id expenseTypeExemptionId
  # @param parent_id taxCodeId
  # @param client_id
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_finance_tax_codes_by_parent_id_expense_type_exemptions_by_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_finance_tax_codes_by_parent_id_expense_type_exemptions
  # Get List of ExpenseTypeExemption
  # @param parent_id taxCodeId
  # @param client_id
  # @param [Hash] opts the optional parameters
  # @option opts [String] :conditions
  # @option opts [String] :child_conditions
  # @option opts [String] :custom_field_conditions
  # @option opts [String] :order_by
  # @option opts [String] :fields
  # @option opts [Integer] :page
  # @option opts [Integer] :page_size
  # @option opts [Integer] :page_id
  # @return [Array<ExpenseTypeExemption>]
  describe 'get_finance_tax_codes_by_parent_id_expense_type_exemptions test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_finance_tax_codes_by_parent_id_expense_type_exemptions_by_id
  # Get ExpenseTypeExemption
  # @param id expenseTypeExemptionId
  # @param parent_id taxCodeId
  # @param client_id
  # @param [Hash] opts the optional parameters
  # @option opts [String] :conditions
  # @option opts [String] :child_conditions
  # @option opts [String] :custom_field_conditions
  # @option opts [String] :order_by
  # @option opts [String] :fields
  # @option opts [Integer] :page
  # @option opts [Integer] :page_size
  # @option opts [Integer] :page_id
  # @return [ExpenseTypeExemption]
  describe 'get_finance_tax_codes_by_parent_id_expense_type_exemptions_by_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_finance_tax_codes_by_parent_id_expense_type_exemptions_count
  # Get Count of ExpenseTypeExemption
  # @param parent_id taxCodeId
  # @param client_id
  # @param [Hash] opts the optional parameters
  # @option opts [String] :conditions
  # @option opts [String] :child_conditions
  # @option opts [String] :custom_field_conditions
  # @option opts [String] :order_by
  # @option opts [String] :fields
  # @option opts [Integer] :page
  # @option opts [Integer] :page_size
  # @option opts [Integer] :page_id
  # @return [Count]
  describe 'get_finance_tax_codes_by_parent_id_expense_type_exemptions_count test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for patch_finance_tax_codes_by_parent_id_expense_type_exemptions_by_id
  # Patch ExpenseTypeExemption
  # @param id expenseTypeExemptionId
  # @param parent_id taxCodeId
  # @param client_id
  # @param patch_operation List of PatchOperation
  # @param [Hash] opts the optional parameters
  # @return [ExpenseTypeExemption]
  describe 'patch_finance_tax_codes_by_parent_id_expense_type_exemptions_by_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_finance_tax_codes_by_parent_id_expense_type_exemptions
  # Post ExpenseTypeExemption
  # @param parent_id taxCodeId
  # @param client_id
  # @param expense_type_exemption expenseTypeExemption
  # @param [Hash] opts the optional parameters
  # @return [ExpenseTypeExemption]
  describe 'post_finance_tax_codes_by_parent_id_expense_type_exemptions test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for put_finance_tax_codes_by_parent_id_expense_type_exemptions_by_id
  # Put ExpenseTypeExemption
  # @param id expenseTypeExemptionId
  # @param parent_id taxCodeId
  # @param client_id
  # @param expense_type_exemption expenseTypeExemption
  # @param [Hash] opts the optional parameters
  # @return [ExpenseTypeExemption]
  describe 'put_finance_tax_codes_by_parent_id_expense_type_exemptions_by_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end
end
