# #Connectwise Manage All Endpoints
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: 2022.1
#
# Generated by: https://openapi-generator.tech
# OpenAPI Generator version: 6.2.1
#

require 'spec_helper'
require 'json'

# Unit tests for ConnectWise::WorkflowEventsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'WorkflowEventsApi' do
  before do
    # run before each test
    @api_instance = ConnectWise::WorkflowEventsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of WorkflowEventsApi' do
    it 'should create an instance of WorkflowEventsApi' do
      expect(@api_instance).to be_instance_of(ConnectWise::WorkflowEventsApi)
    end
  end

  # unit tests for delete_system_workflows_by_parent_id_events_by_id
  # Delete WorkflowEvent
  # @param id eventId
  # @param parent_id workflowId
  # @param client_id
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_system_workflows_by_parent_id_events_by_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_system_workflows_by_parent_id_events
  # Get List of WorkflowEvent
  # @param parent_id workflowId
  # @param client_id
  # @param [Hash] opts the optional parameters
  # @option opts [String] :conditions
  # @option opts [String] :child_conditions
  # @option opts [String] :custom_field_conditions
  # @option opts [String] :order_by
  # @option opts [String] :fields
  # @option opts [Integer] :page
  # @option opts [Integer] :page_size
  # @option opts [Integer] :page_id
  # @return [Array<WorkflowEvent>]
  describe 'get_system_workflows_by_parent_id_events test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_system_workflows_by_parent_id_events_by_id
  # Get WorkflowEvent
  # @param id eventId
  # @param parent_id workflowId
  # @param client_id
  # @param [Hash] opts the optional parameters
  # @option opts [String] :conditions
  # @option opts [String] :child_conditions
  # @option opts [String] :custom_field_conditions
  # @option opts [String] :order_by
  # @option opts [String] :fields
  # @option opts [Integer] :page
  # @option opts [Integer] :page_size
  # @option opts [Integer] :page_id
  # @return [WorkflowEvent]
  describe 'get_system_workflows_by_parent_id_events_by_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_system_workflows_by_parent_id_events_by_id_test
  # Get workflow test results
  # @param id eventId
  # @param parent_id workflowId
  # @param client_id
  # @param [Hash] opts the optional parameters
  # @option opts [String] :conditions
  # @option opts [String] :child_conditions
  # @option opts [String] :custom_field_conditions
  # @option opts [String] :order_by
  # @option opts [String] :fields
  # @option opts [Integer] :page
  # @option opts [Integer] :page_size
  # @option opts [Integer] :page_id
  # @return [Array<Hash<String, Object>>]
  describe 'get_system_workflows_by_parent_id_events_by_id_test test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_system_workflows_by_parent_id_events_count
  # Get Count of WorkflowEvent
  # @param parent_id workflowId
  # @param client_id
  # @param [Hash] opts the optional parameters
  # @option opts [String] :conditions
  # @option opts [String] :child_conditions
  # @option opts [String] :custom_field_conditions
  # @option opts [String] :order_by
  # @option opts [String] :fields
  # @option opts [Integer] :page
  # @option opts [Integer] :page_size
  # @option opts [Integer] :page_id
  # @return [Count]
  describe 'get_system_workflows_by_parent_id_events_count test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for patch_system_workflows_by_parent_id_events_by_id
  # Patch WorkflowEvent
  # @param id eventId
  # @param parent_id workflowId
  # @param client_id
  # @param patch_operation List of PatchOperation
  # @param [Hash] opts the optional parameters
  # @return [WorkflowEvent]
  describe 'patch_system_workflows_by_parent_id_events_by_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_system_workflows_by_parent_id_events
  # Post WorkflowEvent
  # @param parent_id workflowId
  # @param client_id
  # @param workflow_event workflowEvent
  # @param [Hash] opts the optional parameters
  # @return [WorkflowEvent]
  describe 'post_system_workflows_by_parent_id_events test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_system_workflows_by_parent_id_events_by_id_copy
  # Post WorkflowEvent
  # @param id eventId
  # @param parent_id workflowId
  # @param client_id
  # @param [Hash] opts the optional parameters
  # @return [WorkflowEvent]
  describe 'post_system_workflows_by_parent_id_events_by_id_copy test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for put_system_workflows_by_parent_id_events_by_id
  # Put WorkflowEvent
  # @param id eventId
  # @param parent_id workflowId
  # @param client_id
  # @param workflow_event workflowEvent
  # @param [Hash] opts the optional parameters
  # @return [WorkflowEvent]
  describe 'put_system_workflows_by_parent_id_events_by_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end
end
